# Generated by Django 3.0.6 on 2020-05-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_remove_dependants_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependants',
            name='heiNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
