# Generated by Django 3.0.6 on 2020-05-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='securityQuestion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
