# Generated by Django 3.0.6 on 2020-05-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_auto_20200520_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
