# Generated by Django 3.0.6 on 2020-05-28 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_auto_20200529_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependants',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
