# Generated by Django 3.0.6 on 2020-05-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_dependants_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='securityAnswer',
            field=models.CharField(max_length=250),
        ),
    ]
