# Generated by Django 3.0.6 on 2020-06-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0013_auto_20200618_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependants',
            name='first_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
