# Generated by Django 3.0.6 on 2020-06-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0014_auto_20200618_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependants',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
    ]
