# Generated by Django 3.0.6 on 2020-06-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0016_auto_20200629_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(default='English', max_length=20),
        ),
    ]
