# Generated by Django 3.0.8 on 2020-07-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0018_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependants',
            name='heiNumber',
            field=models.CharField(max_length=20),
        ),
    ]
