# Generated by Django 3.0.8 on 2020-07-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0019_auto_20200714_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_facility',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='initial_facility',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
