# Generated by Django 3.0.8 on 2020-07-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0020_auto_20200714_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent',
            field=models.BooleanField(default=True),
        ),
    ]
