# Generated by Django 3.0.8 on 2020-07-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0021_user_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='consent',
        ),
    ]
