# Generated by Django 3.0.8 on 2020-07-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0023_regiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiment',
            name='date_started',
            field=models.DateField(default='2020-05-05'),
        ),
    ]
