# Generated by Django 3.0.8 on 2020-07-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0024_regiment_date_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependants',
            name='CCCNo',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
