# Generated by Django 3.0.6 on 2020-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labResults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='r_id',
            field=models.CharField(max_length=50),
        ),
    ]
