# Generated by Django 3.0.6 on 2020-06-10 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0011_auto_20200603_1436'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labResults', '0002_auto_20200609_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabResult',
            new_name='VLResult',
        ),
        migrations.AlterModelTable(
            name='vlresult',
            table='VLResults',
        ),
        migrations.CreateModel(
            name='EidResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(max_length=50)),
                ('result_type', models.CharField(max_length=10)),
                ('result_content', models.CharField(max_length=30)),
                ('date_collected', models.DateField()),
                ('lab_name', models.CharField(max_length=150)),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.Dependants')),
            ],
            options={
                'db_table': 'EidResults',
            },
        ),
    ]
