# Generated by Django 3.0.8 on 2020-07-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labResults', '0003_auto_20200610_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eidresults',
            name='lab_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vlresult',
            name='lab_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
