# Generated by Django 3.0.8 on 2020-07-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labResults', '0004_auto_20200723_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlresult',
            name='date_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
