# Generated by Django 3.0.8 on 2020-07-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labResults', '0005_vlresult_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eidresults',
            name='date_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
