# Generated by Django 3.0.8 on 2020-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labResults', '0006_eidresults_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eidresults',
            name='owner',
            field=models.CharField(default='Personal', max_length=50),
        ),
    ]
