# Generated by Django 3.0.8 on 2020-07-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labResults', '0007_eidresults_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eidresults',
            name='owner',
        ),
        migrations.AddField(
            model_name='vlresult',
            name='owner',
            field=models.CharField(default='Personal', max_length=50),
        ),
    ]
