# Generated by Django 3.0.8 on 2020-07-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labResults', '0008_auto_20200728_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlresult',
            name='CCCNo',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
