# Generated by Django 3.0.6 on 2020-07-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='appoint_status',
            new_name='app_status',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='appoint_date',
            new_name='appntmnt_date',
        ),
    ]
