# Generated by Django 3.0.8 on 2020-07-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200702_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='aid',
            field=models.CharField(default='00', max_length=50),
        ),
    ]
