# Generated by Django 3.0.8 on 2020-07-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20200708_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appoint_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
