# Generated by Django 3.0.8 on 2020-07-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointments_appoint_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='appoint_type',
            new_name='app_type',
        ),
    ]
