# Generated by Django 3.0.8 on 2020-07-09 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0006_auto_20200708_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='app_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appntmnt_date', models.DateField()),
                ('app_type', models.CharField(max_length=50)),
                ('is_approved', models.CharField(default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Booked_Appointments',
            },
        ),
    ]
