# Generated by Django 3.0.8 on 2020-07-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20200709_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookappointment',
            old_name='is_approved',
            new_name='approval_status',
        ),
    ]
