# Generated by Django 3.0.8 on 2020-07-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20200709_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='dependant',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='owner',
            field=models.CharField(default='Personal', max_length=50),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.Appointments'),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='book_type',
            field=models.CharField(default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
