# Generated by Django 3.0.8 on 2020-07-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_auto_20200709_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='app_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
