# Generated by Django 3.0.8 on 2020-07-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_auto_20200709_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
