# Generated by Django 3.0.6 on 2021-05-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_auto_20200711_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='visit_type',
            field=models.CharField(default='Refill', max_length=50),
        ),
    ]
