# Generated by Django 3.0.6 on 2021-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_auto_20210517_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='visit_type',
            field=models.CharField(default='Scheduled', max_length=50),
        ),
    ]
