# Generated by Django 3.0.6 on 2021-05-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_auto_20210517_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='visit_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
